### ISSUE TITLE
About random forest code

### ISSUE THREAD

**Issue by zkjst110** [zhengxiawu/rethinking_performance_estimation_in_NAS#13]
hello ,i want to know if you have provided the resouce code about the random forest training.

**Comment by zhengxiawu** [comment]
The search process of BPE takes a long long time, therefore, we do not recommend to search the BPE by yourself. Besides, we found that the proposed method is also very similar to https://github.com/automl/fanova, if you do want to search your BPE, the idea is easy to implement with fanova.
