### ISSUE TITLE
Where is the paper?

### ISSUE THREAD

**Issue by leoozy** [zhengxiawu/rethinking_performance_estimation_in_NAS#2]

**Comment by heartInsert** [comment]
I  also  want  to read   it .

**Comment by zhengxiawu** [comment]
We are now applying the corresponding patent for this paper, the paper will be available in April. However, we had already released the NAS search code, feel free to use it and ask questions.

**Comment by zhengxiawu** [comment]
Hi, the paper is publicly available on Arxiv:https://arxiv.org/pdf/2005.09917.pdf
