### ISSUE TITLE
Release the code of BPE and MIP

### ISSUE THREAD

**Issue by slyviacassell** [zhengxiawu/rethinking_performance_estimation_in_NAS#6]
Hi, after reading the repository, I do not find the code for BPE and MIP. Would you mind open source them? Thanks a lot.

**Comment by zhengxiawu** [comment]
Hi, BPE can be found here:https://github.com/zhengxiawu/rethinking_performance_estimation_in_NAS/blob/master/param_setting.py .
As for the MIP, we found that it may useless to release MIP, since 1). the random forest algorithm can be easily found on sklearn. 2)https://github.com/automl/fanova also provides a similar method for hyperparameter analysis. 3) Finding the best BPE in NAS is extremely time consuming(more than 3000 GPU hours).

**Comment by zhengxiawu** [comment]
We have also released the selection of MIP in https://github.com/zhengxiawu/rethinking_performance_estimation_in_NAS/blob/master/experimantal_stastics.xlsx

**Comment by slyviacassell** [comment]
Well, I am just confused with the description of parameter pruning in the paper. So I want to figure out what happend by reading the original code. My questions are as follow.
1). Why  Eq. 9 sets $$ \Theta_i $$ twice?
As far as I am concerned, the description of can be format as follow:
![CodeCogsEqn](https://user-images.githubusercontent.com/22296717/85913766-0d746f00-b86a-11ea-812f-18e783152bdf.gif).
So the description may not match the Eq. 9.
2). If I misunderstand, would you mind geive more details of Eq. 9? 
For instance, what the $$ \cdot $$ in Eq. 9 denote?
![CodeCogsEqn (1)](https://user-images.githubusercontent.com/22296717/85913855-fe41f100-b86a-11ea-956a-066899960968.gif)
Would mind help me to figure out theses problems? Thank you very much!

**Comment by zhengxiawu** [comment]
Sorry for the misunderstanding, in Eq 9 it should be changed to "Θi = βi, i = argminIΘ.", and $$ \cdot $$ is a full stop.

**Comment by slyviacassell** [comment]
Well, that makes sense. Thank you for your patient response! Maybe this  [http://openaccess.thecvf.com/content_CVPR_2020/papers/Zheng_Rethinking_Performance_Estimation_in_Neural_Architecture_Search_CVPR_2020_paper.pdf](open access version) needs minor revisions.
