### ISSUE TITLE
code of BPE

### ISSUE THREAD

**Issue by Kanbo0409** [zhengxiawu/rethinking_performance_estimation_in_NAS#9]
Thanks for releasing the codes, but it seems that codes of search BPE are not included in the releasing codes?

**Comment by zhengxiawu** [comment]
The search process of BPE takes a long long time, therefore, we do not recommend to search the BPE by yourself. Besides, we found that the proposed method is also very similar to https://github.com/automl/fanova, if you do want to search your BPE, the idea is easy to implement with fanova.
